pub mod author_dto_mapper;
pub mod collection_dto_mapper;
pub mod complete_book_dto_mapper;
pub mod create_book_dto_mapper;
pub mod create_collection_dto_mapper;
pub mod create_location_dto_mapper;
pub mod genre_dto_mapper;
pub mod language_dto_mapper;
pub mod location_dto_mapper;
