application: 
  port: 8000
  host: 127.0.0.1
database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: mysql
  database_name: newonlinelibrarian
token:
  secret: test_secret_no_problem_sharing
  expiration_time: 604800